### ISSUE TITLE
Allow to change shortcut which triggers Reedy (ALT+S)

### ISSUE THREAD

**Issue by radmen** [olegcherr/Reedy-for-Chrome#22]
In polish keyboard layout alt+s is reserved for letter *ś*. Right now this triggers Reedy. Would be nice to allow to change this shortcut.

**Comment by olegcherr** [comment]
Reedy allows to change the shortcut.
There is an option named "Shortcut setup" in the popup menu:

![image](https://cloud.githubusercontent.com/assets/3730074/16172728/0ff12964-359f-11e6-82c5-a67403652cdd.png)

**Comment by radmen** [comment]
Oh. Sorry I missed that. Thank you!
