### ISSUE TITLE
Color picker on Mac doesn't work

### ISSUE THREAD

**Issue by corysimmons** [olegcherr/Reedy-for-Chrome#23]
1. settings > color > click swatch
2. opens mac color picker
3. clicking a color in mac color picker doesn't change the swatch

Iridium 51.1
OSX 10.11.5

Happy to help with testing if you need.

(sidenote: great job on Reedy. It's insanely feature-rich and clean)

**Comment by olegcherr** [comment]
Hi and thanks for the issue. I know about it, and unfortunately this is a Chromium's issue.
The only thing I could do is to implement Reedy's own color picker.
There is a task for that problem. May be I'll complete it in the near future.
Thanks again!

**Comment by corysimmons** [comment]
Sounds good.

Personally, I hate system color pickers so I'd be happy with some sort of swatch picker.

Not sure if this is the approach you're looking for, but I've got some swatch picker thingy here if you're interested: https://bit.ly/css-colors (just replace the clipboard action with something that saves the clicked swatch to Reedy settings)

Anyway, not trying to be pushy or anything. Just throwing ideas out there in case it helps.

Again, really appreciate the cool extension.

**Comment by amal** [comment]
Seems to work well now.  Check [in the last version](https://chromewebstore.google.com/detail/reedy-speed-reading/ihbdojmggkmjbhfflnchljfkgdhokffj/reviews?hl=en).
