### ISSUE TITLE
Replace functionality with 'tabs' permission usage (required to restore Reedy in Chrome Web Store)

### ISSUE THREAD

**Issue by art-shen** [olegcherr/Reedy-for-Chrome#31]
Chrome Store removed extension because of policy compliance issue.
Reedy uses 'tabs' permission for user convenience, but it's not considered as a valid reason by Google any more.

While true (almost all functions can work without this permission) such change requires additional time for development.

Any PR for this change can monstrously speed up this process!

**Comment by kingwatam** [comment]
Which features don't work at the moment? Other than runtime errors being reported, Reedy seems to be working (most of the time). I initially thought it stopped working entirely, but it would work again after clicking the icon (which might refresh the extension) and then Alt + S to select text. 

`chrome.tabs.executeScript(tabId == null ? null : tabId, {file: contentScripts[i]});
`

I even tried replacing the above code in \js\background\background.js which is associated with this sort of runtime error. 

```
chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
chrome.tabs.executeScript(tabId == null ? null : tabId, {file: contentScripts[i]});
});
```

It still gives some other error in js/application.js regarding the following line. 

`chrome.runtime.sendMessage(data, callback || function() {});`

I'm not a web developer at all. Anyone with the skills to fix the errors to be accepted by the Store again?

**Comment by andersonpem** [comment]
I'm on the lookout for a developer to tackle this issue. I'm not versed in JavaScript myself.

**Comment by andersonpem** [comment]
I'm no javascript developer as well. I tried to make it work with manifest v3 but it's so damn hard.
https://github.com/andersonpem/Reedy-for-Chrome/tree/feature/v3

**Comment by GoulartNogueira** [comment]
Reedy was AWESOME!
Is the project abandoned?

**Comment by amal** [comment]
@GoulartNogueira it's not abandoned. Although resources for development are very limited at the moment. We are working to restore it in all stores (Google Play, Chrome).

Meanwhile, you can take the latest app or extension builds in the Telegram channel (it is an official Reedy channel):
https://t.me/Reedy_Reader

Android version is also still available in the Huawei App Store and Amazon App Store.

**Comment by amal** [comment]
Finally, Reedy Speed Reading is now back in the store!

https://chromewebstore.google.com/detail/reedy-speed-reading/ihbdojmggkmjbhfflnchljfkgdhokffj?hl=en

Please check it out!
